version: "3"
services:
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    links:
      - influxdb
      - mosquitto
    networks:
      - evohome
  mosquitto:
    image: eclipse-mosquitto:2-openssl
    ports:
      - 1883:1883
    networks:
      - evohome
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
  management-center:
    image: cedalo/management-center:2
    ports:
      - 8088:8088
    depends_on:
      - mosquitto
    links:
      - mosquitto
    networks:
      - evohome
    environment:
      CEDALO_MC_BROKER_ID: mosquitto-2.0
      CEDALO_MC_BROKER_NAME: Mosquitto 2.0
      CEDALO_MC_BROKER_URL: mqtt://mosquitto:1883
      CEDALO_MC_BROKER_USERNAME: cedalo
      CEDALO_MC_BROKER_PASSWORD: 1R1w2KsSHb
      CEDALO_MC_USERNAME: cedalo
      CEDALO_MC_PASSWORD: mmcisawesome
      CEDALO_STREAMSHEETS_ID: streamsheets-local
      CEDALO_STREAMSHEETS_NAME: Streamsheets
      CEDALO_STREAMSHEETS_DESCRIPTION: Local Streamsheets
      CEDALO_STREAMSHEETS_URL: http://localhost:8081
  grafana:
    image: grafana/grafana
    user: 'root'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-config:/etc/grafana/provisioning
      - ./grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SERVER_ENABLE_GZIP=true
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=data/temps.json
    networks:
      - evohome
    restart: unless-stopped
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    networks:
      - evohome
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
  evohome:
    image: evohome:latest
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - evohome
    restart: unless-stopped
    environment:
      - EH-USERNAME=wibble@email.address
      - EH-PASSWORD=5up3r53cr3tp4ssw0rd1
      - OW=true
      - OW-API-KEY=123123123123
      - OW-CITY=London,uk
      - HEALTHCHECKS-IO=https://hc-ping.com/XXXX-YYYY-ZZZZ
networks:
  evohome:
#  cedalo-platform:
#    name: cedalo-platform
#    driver: bridge
volumes:
  influxdb:
  grafana-storage:
